spring:
  profiles:
    active: dev

server:
  port: 9733

acceptor:
  kafka:
    topic:
      deviceLog: device_log

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

